@startuml Criar Conta Google
header <img src="https://cdn.icon-icons.com/icons2/861/PNG/512/Soccer_icon-icons.com_67819.png">
footer <U+00A9> Futebas Esporte e Tecnológicas\nAll rights reserved - [[https://futebas.online futebas.online]]
title <size:20>Jogador_a- Criar Conta</size>
skinparam ParticipantPadding 20
skinparam BoxPadding 10
autonumber
box "Plataforma" #afedaf
  participant Jogador_a
  participant Autenticador
end box


box "Serviços" #fff060
participant Google
end box
Jogador_a -> Autenticador: POST /v1/cadastrar/google 
activate Autenticador #ffffff
Autenticador -> Autenticador: validarJWT()  
activate Google #000000
Autenticador -> Google: resgatarPublicKey()
Autenticador <-- Google: Public Key
deactivate Google
Autenticador -> Autenticador: resgatarClaims
Jogador_a <-- Autenticador: OK
Jogador_a -> Autenticador: POST /v1/login
Autenticador -> Autenticador: validateGoogleJWT()
Jogador_a <-- Autenticador: Usuario Autenticado
deactivate Autenticador
@enduml
